server:
  port: ${port:8086}
spring:
  application:
    name: gray
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/
        metadata:
          version: ${version:1}