spring:
  application:
    name: log
  servlet:
    multipart:
      max-file-size: 600GB
      max-request-size: 600GB
      enabled: true
      file-size-threshold: 600GB
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER
space:
  log:
    log-flag: 1
    mdc:
      enable: true
logging:
  level:
    root: info
  file:
    path: d:/logs