space:
  netty:
    messageItem:
      items:
        - name: mid
          type: ushort
          bytes: 2
          is-kipped: false
          is-package-length: false
        - name : sid
          type: uint
          bytes: 4
          is-kipped: false
          is-package-length: false
        - name: did
          type: uint
          bytes: 4
          is-kipped: false
          is-package-length: false
        - name: bid
          type: uint
          bytes: 4
          is-kipped: false
          is-package-length: false
        - name: no
          type: uint
          bytes: 4
          is-kipped: false
          is-package-length: false
        - name: s1
          type: byte
          bytes: 5
          is-kipped: true
          is-package-length: false
        - name: day
          type: ushort
          bytes: 2
          is-kipped: false
          is-package-length: false
        - name: time
          type: uint
          bytes: 4
          is-kipped: false
          is-package-length: false
        - name: length
          type: ushort
          bytes: 2
          is-kipped: false
          is-package-length: true
      max-packet-size: 1024
      header-packet-size: 32
      version-bytes: 1
      version-value: 0x80
      version-type: ubyte
    tcp-client:
      reconnect-delay-ms: 1000
      retry-max-count: 5
      server-host: 127.0.0.1
      server-port: 9001