spring:
  application:
    name: mybatis-plus
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
space:
  web:
    date-formatter-enable: true