spring:
  application:
    name: web
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    serialization:
      fail-on-empty-beans: false
space:
  common:
    result:
      message: msg
    response-code:
      success-code: 0
  web:
    xssEnable: true
    jacksonCustomize: true

#server:
#  ssl:
#    enabled: true
#    key-store-type: JKS
#    key-store: classpath:localhost.jks
#    key-store-password: changeit
#    key-alias: localhost
#
#    trust-store: classpath:localhost.jks
#    trust-store-password: changeit
#    trust-store-provider: SUN
#    trust-store-type: JKS
#    client-auth: need