spring:
  application:
    name: web
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER
space:
  common:
    result:
      message: msg
    response-code:
      success-code: 0
  web:
    xssEnable: true

