gen:
  project:
    groupId: cn.piesat
    artifactId: test
    version: 1.0.0
    author : zhouxiaoping
    email : zhouxiaoping@piesat.cn
  templates:
    - id: 1
      name: java/Application.java.ftl
      path: ${moduleName}/${bizPath}/src/main/java/${packagePath}/${moduleName}/${moduleName?cap_first}Application.java
      must: 2
      moduleType: 1
    - id: 2
      name: java/Controller.java.ftl
      path: ${moduleName}/${bizPath}/src/main/java/${packagePath}/${moduleName}/controller/${className?cap_first}Controller.java
      must: 1
      moduleType: 1
    - id: 3
      name: java/Service.java.ftl
      path: ${moduleName}/${bizPath}/src/main/java/${packagePath}/${moduleName}/service/${className?cap_first}Service.java
      must: 1
      moduleType: 1
    - id: 4
      name: java/ServiceImpl.java.ftl
      path: ${moduleName}/${bizPath}/src/main/java/${packagePath}/${moduleName}/service/impl/${className?cap_first}ServiceImpl.java
      must: 1
      moduleType: 1
    - id: 5
      name: java/DO.java.ftl
      path: ${moduleName}/${bizPath}/src/main/java/${packagePath}/${moduleName}/model/entity/${className?cap_first}DO.java
      must: 1
      moduleType: 1
    - id: 6
      name: java/DTO.java.ftl
      path: ${moduleName}/${modelPath}/src/main/java/${packagePath}/${moduleName}/model/dto/${className?cap_first}DTO.java
      must: 1
      moduleType: 1
    - id: 7
      name: java/Mapper.java.ftl
      path: ${moduleName}/${bizPath}/src/main/java/${packagePath}/${moduleName}/mapper/${className?cap_first}Mapper.java
      must: 1
      moduleType: 1
    - id: 8
      name: java/VO.java.ftl
      path: ${moduleName}/${modelPath}/src/main/java/${packagePath}/${moduleName}/model/vo/${className?cap_first}VO.java
      must: 1
      moduleType: 1
    - id: 9
      name: java/Query.java.ftl
      path: ${moduleName}/${modelPath}/src/main/java/${packagePath}/${moduleName}/model/query/${className?cap_first}Query.java
      must: 1
      moduleType: 1
    - id: 10
      name: yml/Application.yml.ftl
      path: ${moduleName}/${bizPath}/src/main/resources/application.yml
      must: 2
      moduleType: 1
    - id: 11
      name: xml/Mapper.xml.ftl
      path: ${moduleName}/${bizPath}/src/main/resources/mapper/${moduleName}/${className?cap_first}Mapper.xml
      must: 1
      moduleType: 1
    - id: 12
      name: xml/BizPom.xml.ftl
      path: ${moduleName}/${bizPath}/pom.yml
      must: 2
      moduleType: 1
    - id: 13
      name: xml/Pom.xml.ftl
      path: ${moduleName}/${modelPath}/pom.yml
      must: 2
      moduleType: 2
    - id: 14
      name: js/api.js.ftl
      path: ${moduleName}/vue/src/api/${functionName}Api.js
      must: 1
      moduleType: 1
    - id: 15
      name: vue/index.vue.ftl
      path: ${moduleName}/vue/src/views/${functionName}/index.vue
      must: 1
      moduleType: 1
    - id: 16
      name: vue/add-or-update.vue.ftl
      path: ${moduleName}/vue/src/views/${functionName}/add-or-update.vue
      must: 1
      moduleType: 1
    - id: 17
      name: sql/menu.sql.ftl
      path: ${moduleName}/menu/${tableName}_menu.sql
      must: 1
      moduleType: 1