server:
  port: 8081
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
    web-application-type: reactive
    mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: websocket
          uri: lb:ws://websocket
          predicates:
            - Path=/websocket/**
          filters:
            - SwaggerHeaderFilter
        - id: admin
          uri: lb://admin
          predicates:
            - Path=/admin/**
          filters:
            - SwaggerHeaderFilter
        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/consumer/**
          filters:
            - SwaggerHeaderFilter
        - id: producer
          uri: lb://producer
          predicates:
            - Path=/producer/**
          filters:
            - SwaggerHeaderFilter
        - id: log
          uri: lb://log
          predicates:
            - Path=/*/log/**
          filters:
            - StripPrefix=1
            - SwaggerHeaderFilter
        - id: test-log
          uri: lb://test-log
          predicates:
            - Path=/*/testLog/**
          filters:
            - StripPrefix=1
            - SwaggerHeaderFilter
login:
  ignorePaths:
    - "/admin/user/getLoginPageInfo"
    - "/admin/user/login"
    - "/admin/user/publicKey"
    - "v3"
    - "swagger-resources"
    - "/doc.html"
    - "/swagger-ui.html"
    - "/log/log/add"
    - "goview"
logging:
  level:
    root: debug