server:
  port: 8001
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
    web-application-type: reactive
    mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER
#  redis:
#    host: 192.168.2.100
#    port: 36379
#    database: 1
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/*/consumer/**
          filters:
            - StripPrefix=1
            - SwaggerHeaderFilter
        - id: producer
          uri: lb://producer
          predicates:
            - Path=/*/producer/**
          filters:
            - StripPrefix=1
            - SwaggerHeaderFilter
login:
  ignorePaths:
    - "/admin/user/getLoginPageInfo"
    - "/admin/user/login"
    - "/admin/user/publicKey"
    - "v3"
    - "swagger-resources"
    - "/doc.html"
    - "/swagger-ui.html"
    - "/log/log/add"
    - "goview"