spring:
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      dataSource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://127.0.0.1:3306/test1?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://127.0.0.1:3307/test?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver

#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    jdbc-url: jdbc:mysql://127.0.0.1:3306/test1?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#    hikari:
#      auto-commit: true
#    type: com.zaxxer.hikari.HikariDataSource
#space:
#  datasource:
#    xa:
#      enabled: true
#    dss:
#      master:
#        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/test1?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#        username: root
#        password: 123456
#        key: master
#      slave:
#        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3307/test?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#        username: root
#        password: 123456
#        key: slave
    #pointcut: execution(* cn.piesat.dynamic.datasource.service..*.*(..))
