spring:
  application:
    name: web
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER
space:
  permission:
    url:
      white-list:
        - /test/get2
      user-list:
        - admin
