server:
  servlet:
    context-path: /redis
spring:
  application:
    name: redis
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    cn.piesat.tests.redis: debug
space:
  redis:
    compress-enable: true #开启压缩功能
    prevent-replay-enable: true #开启重刷功能

