spring:
  application:
    name: redis
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
space:
  redis:
    prevent-replay-enable: true #开启重刷功能
    access-limit-enable: true #开启限流功能
springdoc:
  api-docs:
    #是否开启文档功能，默认为true，可不配置
    enabled: true