server:
  servlet:
    context-path: /redis
spring:
  application:
    name: redis
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    redisson:
      file: classpath:redisson.yaml
    lettuce:
      pool:
        enabled: true
        min-idle: 0
        max-active: 8
logging:
  level:
    cn.piesat.tests.redis: debug
space:
  redis:
    compress-enable: true #开启压缩功能
    prevent-replay-enable: true #开启重刷功能
    access-limit-enable: true #开启限流功能
    distributed-lock-enable: true

#https://github.com/redisson/redisson/wiki/2.-Configuration#26-single-instance-mode