spring:
  application:
    name: producer
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/
    loadbalancer:
      nacos:
        enabled: true
server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1
space:
  web:
    date-formatter-enable: true


